In [1]:
from pysus.online_data.Infodengue import download

In [16]:
osasco = download('dengue', '200001', '202312', 'Osasco')
osasco = osasco.transpose()
# to understand the data, access the site https://info.dengue.mat.br/services/tutorial/Python
osasco.head()

,data_iniSE,casos_est,casos_est_min,casos_est_max,casos,p_rt1,p_inc100k,Localidade_id,nivel,id,...,umidmed,umidmin,tempmed,tempmax,casprov,casprov_est,casprov_est_min,casprov_est_max,casconf,notif_accum_year
SE,,,,,,,,,,,,,,,,,,,,,
202312,2023-03-19,140.0,140,140,140,0.995852,18.016905,0,4,353440120231219809,...,78.334258,49.505306,22.551282,28.461538,NaN,NaN,NaN,NaN,NaN,21197
202311,2023-03-12,106.0,106,106,106,0.934226,13.641371,0,4,353440120231119801,...,91.67233,89.528829,20.659091,20.954545,NaN,NaN,NaN,NaN,NaN,21197
202310,2023-03-05,102.0,102,102,102,0.990279,13.126602,0,4,353440120231019795,...,88.515176,85.850233,20.976191,21.428571,NaN,NaN,NaN,NaN,NaN,21197
202309,2023-02-26,90.0,90,90,90,0.990551,11.582296,0,2,353440120230919787,...,85.829629,85.418803,22.268116,22.565217,NaN,NaN,NaN,NaN,NaN,21197
202308,2023-02-19,62.0,62,62,62,0.881663,7.978915,0,3,353440120230819780,...,86.488957,63.334366,21.79515,26.653846,NaN,NaN,NaN,NaN,NaN,21197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201005,2010-01-31,7.0,7,7,7,0.0,1.00008,0,2,353440120100519589,...,79.130046,39.285714,23.753685,32.428571,NaN,NaN,NaN,NaN,NaN,21197
201004,2010-01-24,3.0,3,3,3,0.0,0.428606,0,2,353440120100419589,...,89.152037,67.571429,21.560798,26.142857,NaN,NaN,NaN,NaN,NaN,21197
201003,2010-01-17,2.0,2,2,2,0.0,0.285737,0,1,353440120100319589,...,82.126421,59.428571,23.006908,28.285714,NaN,NaN,NaN,NaN,NaN,21197
201002,2010-01-10,11.0,11,11,11,0.0,1.571554,0,1,353440120100219589,...,75.619946,53.285714,23.625861,28.714286,NaN,NaN,NaN,NaN,NaN,21197
201001,2010-01-03,0.0,0,0,0,0.0,0.0,0,1,353440120100119589,...,78.256411,47.142857,23.559142,30.428571,NaN,NaN,NaN,NaN,NaN,21197

In [24]:
osasco.to_csv('osasco_dengue.csv')